from pgvector.sqlalchemy import VECTOR
"""update embedding dimension to 3072

Revision ID: 1cdec214840c
Revises: 5acd8b8b4553
Create Date: 2026-04-18 20:56:40.766319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cdec214840c'
down_revision: Union[str, Sequence[str], None] = '5acd8b8b4553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_embeddings', 'embedding',
               existing_type=VECTOR(dim=768),
               type_=VECTOR(dim=3072),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_embeddings', 'embedding',
               existing_type=VECTOR(dim=3072),
               type_=VECTOR(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###
