from pgvector.sqlalchemy import Vector
"""create document embeddings table

Revision ID: 5acd8b8b4553
Revises: 35a17cdbd52b
Create Date: 2026-04-18 14:47:45.098597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acd8b8b4553'
down_revision: Union[str, Sequence[str], None] = '35a17cdbd52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('target_document_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['target_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_embeddings_id'), 'document_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_source_document_id'), 'document_embeddings', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_target_document_id'), 'document_embeddings', ['target_document_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_user_id'), 'document_embeddings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_embeddings_user_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_target_document_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_source_document_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    # ### end Alembic commands ###
