"""add s3 storage fields to source documents

Revision ID: 6f055fc53239
Revises: 88af9692bc40
Create Date: 2026-04-28 02:19:40.631914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f055fc53239'
down_revision: Union[str, Sequence[str], None] = '88af9692bc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('storage_provider', sa.String(length=50), nullable=False))
    op.add_column('source_documents', sa.Column('s3_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 's3_key')
    op.drop_column('source_documents', 'storage_provider')
    # ### end Alembic commands ###
