"""add semantic similarity to analysis results

Revision ID: 81e1734a4705
Revises: 2da1452ece92
Create Date: 2026-04-22 18:47:11.770827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e1734a4705'
down_revision: Union[str, Sequence[str], None] = '2da1452ece92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('semantic_similarity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'semantic_similarity')
    # ### end Alembic commands ###
