from pgvector.sqlalchemy import Vector
"""create source documents chunks tables

Revision ID: 88af9692bc40
Revises: 81e1734a4705
Create Date: 2026-04-23 02:46:18.995440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88af9692bc40'
down_revision: Union[str, Sequence[str], None] = '81e1734a4705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_document_chunks_id'), 'source_document_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_source_document_chunks_source_document_id'), 'source_document_chunks', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_source_document_chunks_user_id'), 'source_document_chunks', ['user_id'], unique=False)
    op.create_table('source_document_chunk_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('embedding', Vector(dim=3072), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_document_chunk_embeddings_chunk_id'), 'source_document_chunk_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_source_document_chunk_embeddings_id'), 'source_document_chunk_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_source_document_chunk_embeddings_source_document_id'), 'source_document_chunk_embeddings', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_source_document_chunk_embeddings_user_id'), 'source_document_chunk_embeddings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_document_chunk_embeddings_user_id'), table_name='source_document_chunk_embeddings')
    op.drop_index(op.f('ix_source_document_chunk_embeddings_source_document_id'), table_name='source_document_chunk_embeddings')
    op.drop_index(op.f('ix_source_document_chunk_embeddings_id'), table_name='source_document_chunk_embeddings')
    op.drop_index(op.f('ix_source_document_chunk_embeddings_chunk_id'), table_name='source_document_chunk_embeddings')
    op.drop_table('source_document_chunk_embeddings')
    op.drop_index(op.f('ix_source_document_chunks_user_id'), table_name='source_document_chunks')
    op.drop_index(op.f('ix_source_document_chunks_source_document_id'), table_name='source_document_chunks')
    op.drop_index(op.f('ix_source_document_chunks_id'), table_name='source_document_chunks')
    op.drop_table('source_document_chunks')
    # ### end Alembic commands ###
